<a href="https://colab.research.google.com/github/andrecsq/ad_ufrj/blob/main/chapter3/Andr%C3%A9_Queiroz_AD_3_31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### For the network graph in Figure 3.17, find the PageRank for the nodes of the network using a damping factor of p = 0.90. See Example 3.21.



![image.png](https://i.imgur.com/SFngnjJ.png)

PageRank formula: $$P = pQ + (1-p)A$$

In [ ]:
import numpy as np

In [ ]:
sz = 4
p = 0.9

Q = np.array([[0,1/2,1/2,0],
              [0,0,1,0],
              [1/3,1/3,0,1/3],
              [1/4,1/4,1/4,1/4]])
print("Q:")
print(Q)

Q:
[[0.         0.5        0.5        0.        ]
 [0.         0.         1.         0.        ]
 [0.33333333 0.33333333 0.         0.33333333]
 [0.25       0.25       0.25       0.25      ]]


In [ ]:
A = np.ones((sz,sz))/sz
print("A:")
print(A)

A:
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]


In [ ]:
PR = p*Q + (1-p)*A

print("PageRank matrix:")
print(PR)

PageRank matrix:
[[0.025 0.475 0.475 0.025]
 [0.025 0.025 0.925 0.025]
 [0.325 0.325 0.025 0.325]
 [0.25  0.25  0.25  0.25 ]]


In [ ]:
PR100 = np.linalg.matrix_power(PR, 100)

print(f"Stationary probabilities: {PR100[0,:]}")

Stationary probabilities: [0.17955801 0.26035912 0.38052486 0.17955801]


Ajudinha pra questão 3.38

In [ ]:
Q = np.array([[0.402, 0.402, 0.161, 0.032, 0.003],
              [0.000, 0.482, 0.386, 0.116, 0.015],
              [0.000, 0.000, 0.579, 0.347, 0.069],
              [0.000, 0.000, 0.000, 0.694, 0.278],
              [0.000, 0.000, 0.000, 0.000, 0.833],])

I = np.identity(5)

F = np.linalg.inv(I - Q)

F

array([[1.6722408 , 1.29776217, 1.82937522, 2.74132457, 5.46585793],
       [0.        , 1.93050193, 1.7700089 , 2.73899121, 5.46423772],
       [0.        , 0.        , 2.37529691, 2.69355565, 5.46529316],
       [0.        , 0.        , 0.        , 3.26797386, 5.44010019],
       [0.        , 0.        , 0.        , 0.        , 5.98802395]])

In [ ]:
np.sum(F[0])

13.006560678640929